### ISSUE TITLE
FAKING NAROCA MI HRONOUKO OBESTE SE

### ISSUE THREAD

**Issue by XzvezdanX** [jakecernet/KrokyPlus#23]
Help Lin

**Comment by jakecernet** [comment]
> Nocm hrenouke

ja a si blacklistu pa use

**Comment by XzvezdanX** [comment]
Faking nastavitu mas za brez "hrenouke" lahko bi delala ce je ze not

**Comment by XzvezdanX** [comment]
Vem on je peder

**Comment by jakecernet** [comment]
hahhaahhahahttps://github.com/jakecernet/KrokyPlus/assets/117542696/64ce620f-43c3-4665-bc16-85817d55accb

**Comment by majmohar4** [comment]
![1000017114](https://github.com/jakecernet/KrokyPlus/assets/119863703/37473378-3e78-4deb-a530-87843a0f0c1e)

**Comment by jakecernet** [comment]
ne Mohar dost je
